force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>customer object</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <description>customer object</description>
    <label>Event registration</label>
    <nameField>
        <label>Event Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events registration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Attendee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Events registration</relationshipLabel>
    <relationshipName>Events_Registration</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Events registration</relationshipLabel>
    <relationshipName>Events_Registration</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/RegistrationDate__c.field-meta.xml
<CustomField>
    <fullName>RegistrationDate__c</fullName>
    <label>RegistrationDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/InvoicePDFController.cls
public with sharing class InvoicePDFController {
    public class DataPDFController {
        public Date eventDate { get; set; }
        public String eventName { get; set; }
        public String attendeeName { get; set; }
        public Date regDate { get; set; }
        public String regId { get; set; }

        public DataPDFController() {
            eventDate    = null;
            eventName    = '';
            attendeeName = '';
            regDate      = null;
            regId        = '';   
        }
    }
    public DataPDFController data { get; set; }
    
    public InvoicePDFController() {        
        this.data = new DataPDFController();        

        String regId = ApexPages.currentPage().getParameters().get('registrationId');        
        if (regId != null) {
            Event_Registration__c registration = [SELECT Id, RegistrationDate__c, Event__r.Name, Event__r.Date__c, Attendee__r.Name, Attendee__r.Email FROM Event_Registration__c WHERE Id = :regId LIMIT 1];
            if (registration != null) {
                data.regDate = registration.RegistrationDate__c; 
                data.regId = String.valueOf(registration.Id); 
                if (registration.Event__r != null) {
                    data.eventDate = registration.Event__r.Date__c;
                    data.eventName = registration.Event__r.Name; 
                    data.attendeeName = registration.Attendee__r.Name; 
                }               
            }            
        }
    }

}