force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>customer object</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/AvailableSeats__c.field-meta.xml
<CustomField>
    <fullName>AvailableSeats__c</fullName>
    <label>Available seats</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/MaxAttendees__c.field-meta.xml
<CustomField>
    <fullName>MaxAttendees__c</fullName>
    <defaultValue>$CustomMetadata.Event_Setting__mdt.Default.Max_available_seats__c</defaultValue>
    <label>Max attendees</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/Event_Registration__c.object-meta.xml
<CustomObject>
    <description>customer object</description>
    <label>Event registration</label>
    <nameField>
        <label>Event Registration Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events registration</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event_Registration__c/fields/Attendee__c.field-meta.xml
<CustomField>
    <fullName>Attendee__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Attendee</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Events registration</relationshipLabel>
    <relationshipName>Events_Registration</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Event_Registration__c/fields/Event__c.field-meta.xml
<CustomField>
    <fullName>Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Event</label>
    <referenceTo>Event__c</referenceTo>
    <relationshipLabel>Events registration</relationshipLabel>
    <relationshipName>Events_Registration</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EventRegistrationTriggerHandlerTest.cls
@isTest
public class EventRegistrationTriggerHandlerTest {
    
    @testSetup
    static void setupTestData() {
        Event__c testEvent = new Event__c(
            Name = 'Event for Users',
            MaxAttendees__c = 100,
            AvailableSeats__c = 50,
            Date__c = Date.newInstance(2024, 1, 1),
            Location__c = 'Kyiv'
        );
        insert testEvent;
        
        Contact testContact = new Contact(
            LastName = 'User Name',
            FirstName = 'Test Name',
            Email = 'testuser@gmail.com'
        );
        insert testContact;
        
        Event_Registration__c reg = new Event_Registration__c(
            Event__c = testEvent.Id,
            Attendee__c = testContact.Id
        );
        insert reg;
    }
    
    static testMethod void testHandleTrigger_Before() {
        Event_Registration__c reg = [SELECT Id, Event__c, Attendee__c, Name FROM Event_Registration__c LIMIT 1];
        
        List<Event_Registration__c> triggerListNew = new List<Event_Registration__c>{ reg };
        List<Event_Registration__c> triggerListOld = new List<Event_Registration__c>();
        Map<Id, Event_Registration__c> triggerMapNew = new Map<Id, Event_Registration__c>{ reg.Id => reg };
        Map<Id, Event_Registration__c> triggerMapOld = new Map<Id, Event_Registration__c>();
        
        Test.startTest();
        EventRegistrationTriggerHandler.handleTrigger(
            false, // isInsert
            false, // isUpdate
            false, // isDelete
            true,  // triggerisBefore
            false, // triggerisAfter
            triggerListNew,
            triggerListOld,
            triggerMapNew,
            triggerMapOld
        );
        Test.stopTest();
        
        reg = [SELECT Name FROM Event_Registration__c WHERE Id = :reg.Id];
        String supposedName = 'Event for Users (Test Name User Name)';
        System.assertEquals(supposedName, reg.Name, 'Registration name should be generated correctly in before context.');
    }
    
    @isTest
    private static void testHandleTrigger_After() {        
        Event__c testEvent = [SELECT Id, Name, Date__c, Location__c FROM Event__c LIMIT 1];
        Contact testContact = [SELECT Id, Name, Email FROM Contact LIMIT 1];
        Event_Registration__c newReg = new Event_Registration__c(
            Event__c = testEvent.Id,
            Attendee__c = testContact.Id
        );
        insert newReg;
        
        List<Event_Registration__c> triggerListNew = new List<Event_Registration__c>{ newReg };
        List<Event_Registration__c> triggerListOld = new List<Event_Registration__c>{ newReg };
        Map<Id, Event_Registration__c> triggerMapNew = new Map<Id, Event_Registration__c>{ newReg.Id => newReg };
        Map<Id, Event_Registration__c> triggerMapOld = new Map<Id, Event_Registration__c>{ newReg.Id => newReg };
        
        Test.startTest();
        EventRegistrationTriggerHandler.handleTrigger(
            true,  // isInsert
            false, // isUpdate
            false, // isDelete
            false, // triggerisBefore
            true,  // triggerisAfter
            triggerListNew,
            triggerListOld,
            triggerMapNew,
            triggerMapOld
        );
        Test.stopTest();
        
        // check email sending limits
        Integer emailInvocations = Limits.getEmailInvocations();
        System.debug('emailInvocations: ' + emailInvocations);
        System.assert(emailInvocations > 0, 'At least one email should be sent in after trigger context.');
    }
}