force-app/main/default/objects/Event__c/Event__c.object-meta.xml
<CustomObject>
    <description>customer object</description>
    <label>Event</label>
    <nameField>
        <label>Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Event__c/fields/Actual__c.field-meta.xml
<CustomField>
    <fullName>Actual__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Actual</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/AvailableSeats__c.field-meta.xml
<CustomField>
    <fullName>AvailableSeats__c</fullName>
    <label>Available seats</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/DateTime__c.field-meta.xml
<CustomField>
    <fullName>DateTime__c</fullName>
    <label>Time</label>
    <type>Time</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/MaxAttendees__c.field-meta.xml
<CustomField>
    <fullName>MaxAttendees__c</fullName>
    <defaultValue>$CustomMetadata.Event_Setting__mdt.Default.Max_available_seats__c</defaultValue>
    <label>Max attendees</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Event__c/fields/Type_of_event__c.field-meta.xml
<CustomField>
    <fullName>Type_of_event__c</fullName>
    <label>Type of event</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Webinar</fullName>
            </value>
            <value>
                <fullName>Conference</fullName>
            </value>
            <value>
                <fullName>Training</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EventController.cls
public with sharing class EventController {
    
    //@AuraEnabled(cacheable=true)
    @AuraEnabled
    public static List<Event__c> getAvailableEvents() {
        return [SELECT Id, Name, Type_of_event__c, Date__c, DateTime__c, Location__c, AvailableSeats__c, MaxAttendees__c 
                FROM Event__c 
                WHERE Actual__c = true AND AvailableSeats__c > 0 
                ORDER BY Date__c ASC];
    }
    
}